[32m2025-07-03 00:34:29 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - ec3aa63c-75d1-4531-983d-c88955732023 - 535095 - LOGS_CAPTURED - Started capturing logs in process (pid: 535095).
[32m2025-07-03 00:34:29 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - ec3aa63c-75d1-4531-983d-c88955732023 - 535095 - model_registry_update - STEP_START - Started execution of step "model_registry_update".
[32m2025-07-03 00:34:29 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - ec3aa63c-75d1-4531-983d-c88955732023 - model_registry_update - Loading file from: /workspaces/data-scientist-at-magenta/dagster_home/storage/validate using PickledObjectFilesystemIOManager...
[32m2025-07-03 00:34:30 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - ec3aa63c-75d1-4531-983d-c88955732023 - 535095 - model_registry_update - LOADED_INPUT - Loaded input "validate" using input manager "io_manager", from output "result" of step "validate"
[32m2025-07-03 00:34:30 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - ec3aa63c-75d1-4531-983d-c88955732023 - 535095 - model_registry_update - STEP_INPUT - Got input "validate" of type "Any". (Type check passed).
[32m2025-07-03 00:34:30 +0000[0m - dagster - [34mINFO[0m - __ASSET_JOB - ec3aa63c-75d1-4531-983d-c88955732023 - model_registry_update - Starting model registry update process
[32m2025-07-03 00:34:30 +0000[0m - dagster - [34mINFO[0m - __ASSET_JOB - ec3aa63c-75d1-4531-983d-c88955732023 - model_registry_update - Storing new model in registry
[32m2025-07-03 00:34:30 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - ec3aa63c-75d1-4531-983d-c88955732023 - model_registry_update - Error updating model registry: dump() missing 1 required positional argument: 'fp'[0m
[32m2025-07-03 00:34:30 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - ec3aa63c-75d1-4531-983d-c88955732023 - 535095 - model_registry_update - STEP_FAILURE - Execution of step "model_registry_update" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "model_registry_update"::

TypeError: dump() missing 1 required positional argument: 'fp'

Stack Trace:
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 56, in op_execution_error_boundary
    yield
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 480, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 127, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 115, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/src/code_location_interview/code_location_interview/assets/training.py", line 417, in model_registry_update
    json.dump(metadata),
    ^^^^^^^^^^^^^^^^^^^
[0m
