[32m2025-07-02 23:27:16 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - e53295ae-d78d-4a53-ab9e-551775f1b2de - 312289 - LOGS_CAPTURED - Started capturing logs in process (pid: 312289).
[32m2025-07-02 23:27:16 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - e53295ae-d78d-4a53-ab9e-551775f1b2de - 312289 - predictions - STEP_START - Started execution of step "predictions".
[32m2025-07-02 23:27:16 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - e53295ae-d78d-4a53-ab9e-551775f1b2de - predictions - Loading file from: /workspaces/data-scientist-at-magenta/dagster_home/storage/current_model using PickledObjectFilesystemIOManager...
[32m2025-07-02 23:27:16 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - e53295ae-d78d-4a53-ab9e-551775f1b2de - 312289 - predictions - LOADED_INPUT - Loaded input "current_model" using input manager "io_manager", from output "result" of step "current_model"
[32m2025-07-02 23:27:16 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - e53295ae-d78d-4a53-ab9e-551775f1b2de - predictions - Loading file from: /workspaces/data-scientist-at-magenta/dagster_home/storage/processed_features using PickledObjectFilesystemIOManager...
[32m2025-07-02 23:27:16 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - e53295ae-d78d-4a53-ab9e-551775f1b2de - 312289 - predictions - LOADED_INPUT - Loaded input "processed_features" using input manager "io_manager"
[32m2025-07-02 23:27:16 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - e53295ae-d78d-4a53-ab9e-551775f1b2de - 312289 - predictions - STEP_INPUT - Got input "current_model" of type "Any". (Type check passed).
[32m2025-07-02 23:27:16 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - e53295ae-d78d-4a53-ab9e-551775f1b2de - 312289 - predictions - STEP_INPUT - Got input "processed_features" of type "Any". (Type check passed).
[32m2025-07-02 23:27:16 +0000[0m - dagster - [34mINFO[0m - __ASSET_JOB - e53295ae-d78d-4a53-ab9e-551775f1b2de - predictions - Starting prediction generation
[32m2025-07-02 23:27:16 +0000[0m - dagster - [34mINFO[0m - __ASSET_JOB - e53295ae-d78d-4a53-ab9e-551775f1b2de - predictions - Using model: ID: model_001
[32m2025-07-02 23:28:58 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - e53295ae-d78d-4a53-ab9e-551775f1b2de - 312289 - predictions - STEP_FAILURE - Execution of step "predictions" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "predictions"::

duckdb.duckdb.IOException: IO Error: Could not set lock on file "/workspaces/data-scientist-at-magenta/src/code_location_interview/code_location_interview/dwh/database.duckdb": Conflicting lock is held in /workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/bin/python3.12 (PID 296838). See also https://duckdb.org/docs/connect/concurrency

Stack Trace:
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 56, in op_execution_error_boundary
    yield
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 480, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 127, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 115, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/src/code_location_interview/code_location_interview/assets/predict.py", line 98, in predictions
    with database.get_connection() as conn:
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster_duckdb/resource.py", line 62, in get_connection
    conn = backoff(
           ^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_utils/backoff.py", line 71, in backoff
    raise to_raise
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_utils/backoff.py", line 65, in backoff
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
[0m
